apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgARbutL/WEnW/ypflFO4sEhm1D/mDoqAFO9WXrIdUDlzE4CIe6rmEeHxBjBpEuAlWCGSZUJlKpYyDjJOi9X8oD2Dq10LmhQoydKw3SxLvAGWDCGVh/qvo5aqpCQPHo2hRk8mQPg+t5JGcXLgcsg83gZfXQVCM0ghO3JcgCW32WGAA4N18rGXk5mHRoZLRXY8qhko79njyJMfxn4ETW4q6YyvAyeyce+cPNdCnPF8sp2FuZyykrliaVvmC0IOTfJo2knB62sooINRMUKBZXlEr5d1Lkr0sUm0IR6tmRmfBxlvbqm9+xtGk7Gn3gGY8n2MjakpTwIBOFZopoBlI19niMGIbp8Tg5nvONKkNfXdRFaSmAkbL+8zhUexi7ItjSC0OHSqVFlKWuBY2R5KeyBqCXe7WQRO98oV0rvbcN0yxqWCOU694KIBh316jpjdRG0Ps9OzAem9fJp9NIriWTfE93uKr53kZ+U6cafmofDDZzFWLCxapGyZhKiUvAkpWUy8nrrYWnpRtSZWtDcVbpQviPCbM41QldvQMfxAttPnbOvjP0HF6TE4eUovTuqCsTqSjpuU5D1V9promWFm5D/2L4V06yCUG6tnJ1Dbdelx9+jgztYkyvOGPWMsOmztoBJOvcGNi9WhdwVcTgkThFMQdvNDquEwXnv1+PJ3VXQxw6cwarrGZArTvWCq9WlE5bIgidoaKqpWO0S+op+wCvydH9ku7C7r2aJf1bz2vA+rDasNcRmpQhxqIsHTf42ZVc9JPEIh9iDJT8PjwfOVHUqRm6WdCFjojdY7eFJnc+YzqJNE26pRHhp9tlVy0A6IP0L1X/UpKEP/ZFfPEKTj9zeHP55sLdxRrQdimgRZk7l1jcLfZqC5pwcNmyBxqP6O2/TSRGdfaWHDCIFQz9cD4Bsyn6BxmPun25anHsIpolnzQwB2g==
    IBM_ENTITLED_REGISTRY_USER: AgAW0Ns8H4XWOyj9QSDyps9vEFMWhjEJ749cHaaCHNNJ22thA/m+SYxO6KtUavIugm7nZ+wDPSav83B97X0fWrpyeqGga+IpjX4I3aOEiyIdDmdBH/o1BV9xIwokfN53IhAmH8s9IRUIiwgJPsJBvnv9rT6+vEpfZyiARoXm9dzJNba0E2diZAhSGzSOv7obblChf1PCx06InxoiRe2zJo46lTJ/mDBFnH6MmRHqpsUCHHxrbhFfxu1yNMLlw+wq2jRcBFBuHgNovM9ArPujefLOgmPickLzyxmuhG62RLjCbYrzIm+gGZB481VC+Bg00Fo/flN5QDP6eGXEGFJX2uoOFgAm92XyJT6NRyzchZ6RuijSdUYnUA7D+cMBtUH/+2VSAsTPrLR7PL36A0TQteJFDlyDKlIHRF/F+LSJ0F+kgtszo48Am+oyONm4e5ZUulCo8onB/RpI9XPnSj7MpLjbZu0OJ+nJTABwDQHRr6aoJi7+i8rxvNIedoAF3eigOOkGjnRdIMJucjp5BM27iPVrkLC16HlN1WORXQTnRj2jy0013ocAU8Iw0u6MHTeMYIm6V6Lza1w7WM7Ax7WI03V+Ha5hf+nF9AweUd0ZeiWazFm9EQMS3sDlDrQBxhQ5uDQ0zpc9wD8zLYz0d+ExNqqLkuOND76SZ2TKq/kGG2+FU0ySrzlWtPXUgDTmAHgGjxe2XA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

